set -g mouse on
set -g prefix C-s              
setw -g mode-keys vi           
set -s escape-time 0           
set -g base-index 1           
setw -g pane-base-index 1    
set -g renumber-windows on  

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

rose_pine_base="#191724"
rose_pine_gold="#f6c177"
rose_pine_rose="#ebbcba"
rose_pine_pine="#9ccfd8"
rose_pine_subtle="#908caa"
rose_pine_surface="#1f1d2e"

set -g status-position bottom
set -g status-justify left
set -g status-style bg=default
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[fg=$rose_pine_rose,bg=default]#[fg=$rose_pine_base,bg=$rose_pine_rose,bold] #S#[fg=$rose_pine_rose,bg=default] "
setw -g window-status-separator "" 
setw -g window-status-format "#[fg=$rose_pine_surface,bg=default] #[fg=$rose_pine_subtle,bg=default]#I:#W#[fg=$rose_pine_surface,bg=default]"
setw -g window-status-current-format "#[fg=$rose_pine_pine,bg=default]#[fg=$rose_pine_base,bg=$rose_pine_pine,bold]#I:#W#[fg=$rose_pine_pine,bg=default] "
set -g status-right ""

bind r source-file ~/.tmux.conf \; display "Config Reloaded!"
